Feed in kg/h: 7
Pressure: 1400.93
Feed Temperature in °C: 82.65
Mass Fraction OME: OME1-0.3576 OME2-0.1895 OME3-0.0285 OME4-0.0034 OME5-0.0101 OME6-0.0005
Mass Fraction Methyl formate, Methanol, Formaldehyde, and water: MeFo-0.0007 MeOh-0.1821
  FA-0.2167 WA-0.0386
Reflux Ratio: 0.5
Bottom Flow Rate: 0.59
