Head Pressure C1: 982 mbar
Head Pressure C2: 982 mbar
Feed Flow Rate to C1: 4.3 kg/hr
Feed Composition to C1: water, n-butanol by mass
Feed Composition to C2: water,  n-butanol by mass
AnomalyReasons: No anomaly, training data
