Feed in kg/h: 7
Pressure: 1394.92
Feed Temperature in °C: 84.24
Feed composition in mass fraction OME: OME1-0.2313, OME2-0.1263, OME3-0.0525, OME4-0.0004,
  OME5-0.0001, OME6-0.0000
Feed composition in mass fraction Methyl formate, Trioxan, Methanol, Formaldehyde and water: MeFo-0.0004,
  Trioxan-0.0000, MeOh-0.1688, FA-0.2405, WA-0.0298
Reflux Ratio: 0.5
Bottom Flow Rate: 0.13
Anomaly Reasons: No Anomaly
