Head Pressure C1: 960 mbar
Head Pressure C2: 960 mbar
Feed Flow Rate to C1: 4.2 kg/hr
Feed Composition to C1: 0.932 water, 0.068 n-butanol
Feed Composition to C2: 0.094 water, 0.906 n-butanol
AnomalyReasons: No anomaly
