Feed in kg/h: 6.17
Pressure: 1391.86
Feed Temperature in °C: 85.71
Feed Composition in Mass Fraction OME: OME1-0.3755, OME2-0.1977, OME3-0.0264, OME4-0.0033,
  OME5-0.0013 OME6-0.0005
Feed Composition in Mass Fraction Methyl Formate and Methanol: MeFo-0.0007 and MeOh-0.1907
Reflux Ratio: 0.5
Bottom Flow Rate: 0.47
Anomaly Reasons: No anomaly
