Head Pressure C1: 978 mbar
Head Pressure C2: 978 mbar
Feed Flow Rate to C1: 4.4 kg/hr
Feed Composition to C1: water, n-butanol by mass
Feed Composition to C2: water,  n-butanol by mass
AnomalyReasons: No anomaly, training data
